// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrcjEbODIOuuZ9jcFkNYHYwCH3kblpx6Y',
    appId: '1:819533831400:web:730daed60ce24ec5bcfd5d',
    messagingSenderId: '819533831400',
    projectId: 'notekeep-5d1e3',
    authDomain: 'notekeep-5d1e3.firebaseapp.com',
    storageBucket: 'notekeep-5d1e3.appspot.com',
    measurementId: 'G-KQMY6DW8MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiRX4xyp0hoSYjGHehJ_9ga4d4OniY63A',
    appId: '1:819533831400:android:ea602d846d6c93abbcfd5d',
    messagingSenderId: '819533831400',
    projectId: 'notekeep-5d1e3',
    storageBucket: 'notekeep-5d1e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDroJJiy4wuPFZrFPKKbU40HwaooHqAeqQ',
    appId: '1:819533831400:ios:9dfffbfcfafa6528bcfd5d',
    messagingSenderId: '819533831400',
    projectId: 'notekeep-5d1e3',
    storageBucket: 'notekeep-5d1e3.appspot.com',
    iosBundleId: 'com.example.notekeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDroJJiy4wuPFZrFPKKbU40HwaooHqAeqQ',
    appId: '1:819533831400:ios:a05368250c7e9566bcfd5d',
    messagingSenderId: '819533831400',
    projectId: 'notekeep-5d1e3',
    storageBucket: 'notekeep-5d1e3.appspot.com',
    iosBundleId: 'com.example.notekeep.RunnerTests',
  );
}
